name: cettalks1
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  url_launcher: ^5.4.10
  google_fonts: ^1.1.0
  just_audio: ^0.1.10
  font_awesome_flutter: ^8.8.1
  audio_service: ^0.11.0
  http: ^0.12.1
  social_media_widgets: ^1.0.0+2
  cloud_firestore: ^0.13.6
  firebase_messaging: ^6.0.16
  volume: ^0.1.4
  sleek_circular_slider: ^1.1.0
  sliding_up_panel: ^1.0.2
  flutter_blurhash: ^0.5.0
  fluttertoast: ^4.0.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  



  
  


flutter:

  uses-material-design: true

  assets:
    - assets/images/cetalks.png
    - assets/images/load.gif
    

  fonts:
    - family: BalooChettan2
      fonts:
        - asset: assets/fonts/BalooChettan2-Regular.ttf
 
